### ISSUE TITLE
Modificar metodos que retornan Promos

### ISSUE THREAD

**Issue by gusanchez** [gusanchez/Geofencing#105]
Se tienen que modificar los metodos agregandole el ***id del usuario*** para que devuelva las Promos con la validacion del campo Favoritos:

- [x] GET /buscar?search=ca&usuario_id=166

Parametros:
- search: valor de la busqueda
- usuario_id: id del usuario para la validacion en Favoritos

---------------------------------------------------------
- [x] GET /promo/categoria-por-padre?idCat=3&idUsuario=152

Parametros:
- idCat: id de la categoria padre
- idUsuario: id del usuario para la validacion en Favoritos

---------------------------------------------------------
- [x] GET /promo/categoria?id=1&idUser=152
***ESTE METODO NO HAY QUE MODIFICARLO, SOLO PROBARLO***

Parametros:
- id: id de la categoria
- idUser: id del usuario para la validacion en Favoritos

---------------------------------------------------------
- [x] GET /promo/categoria-por-padre-sucur?id=4&coordX=-34.5876684&coordY=-58.4400317&idUsuario=152

Parametros:
- id: id de la categoria padre
- coordX: coordenada x del usuario
- coordY: coordenada y del usuario
- idUsuario: id del usuario para la validacion en Favoritos

---------------------------------------------------------
- [ ] GET /promo/categoria-por-usuario?idUsuario=152

Parametro:
- idUsuario: id del usuario para la validacion en Favoritos

---------------------------------------------------------

***Todos los metodos devuelven una lista de promos agregandole el parametro "favorito":***

{
        "id": 18,
        "nombre": "Flyermob",
        "url_lista": "https://flyermob.s3.amazonaws.com/clients/octagon/promos_prueba/BIENVENIDA-lista.jpg",
        "url_detalle": "https://flyermob.s3.amazonaws.com/clients/octagon/promos_prueba/BIENVENIDA-detalle.jpg",
        "tipo": 0,
        "mensaje": "Muy pronto!!",
        "sucursal_id": null,
        "reglas_id": 4,
        "categoria_id": 18,
        "fecha_inicio": "2017-01-23 12:55:29",
        "fecha_fin": "2017-02-19 12:55:29",
        "favorito": true
    },
    {
        "id": 12,
        "nombre": "Web",
        "url_lista": "https://flyermob.s3.amazonaws.com/clients/octagon/promos_prueba/oferta-1-hor.png",
        "url_detalle": "http://www.flyermob.com",
        "tipo": 1,
        "mensaje": "Visita nuestra pagina y conoce mas!!",
        "sucursal_id": null,
        "reglas_id": 3,
        "categoria_id": 21,
        "fecha_inicio": "2017-01-23 12:55:28",
        "fecha_fin": "2017-02-15 12:55:28",
        "favorito": false
    },
